accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [

    # Default Sign Up Page
    path('signup/',
         SignUpView.as_view(),
         name='signup')
]

api/urls.py
from django.urls import path
from.views import APIList, APIDetail

urlpatterns = [
    path('<int:pk>/',
         APIDetail.as_view()),

    path('',
         APIList.as_view()),
]

config/urls.py
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    # Points to the urls.py Incident App (Incident List)
    path('incidents/', include('incidents.urls')),

    # Default API URL - API Homepage
    path('api/v1/', include('api.urls')),

    # Default API Auth URL - Login and Logout functionality
    path('api-auth/', include('rest_framework.urls')),

    # Points to urls.py Pages app (HomePage)
    path('', include('pages.urls')),

    path('api/schema/', SpectacularAPIView.as_view(), name='api-schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='api-schema'), name='api-docs')
]

incidents/urls.py
from django.shortcuts import render

from django.urls import path
from .views import (
    HomeListView,
    HomeDetailView,
    HomeCreateView,
    HomeUpdateView,
    HomeDeleteView
)

urlpatterns = [

    # Delete Incident URL
    path('<int:pk>/delete/',
         HomeDeleteView.as_view(),
         name='incidents/incident_delete'),

    # Update Incident URL
    path('<int:pk>/edit/',
         HomeUpdateView.as_view(),
         name='incidents/incident_edit'),

    # New Incident URL
    path('new/',
         HomeCreateView.as_view(),
         name='incidents/incident_new'),

    # Detailed URL by PK Key
    path('<int:pk>/',
         HomeDetailView.as_view(),
         name='incidents/incident_detail'),

    # Incident List URL
    path('',
         HomeListView.as_view(),
         name='incidents/incident_list'),
]

pages/urls.py
from django.urls import path
from .views import HomePageView

urlpatterns = [

    # Default Homepage URL
    path('',
         HomePageView.as_view(),
         name='home'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)

customers/models.py
from django.db import models

# Create your models here.

incidents/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
# Create your models here.
incident_type = (
    ("Inadvertent Data Exposure", "Inadvertent Data Exposure"),
    ("Security Misconfiguration", "Security Misconfiguration"),
    ("Product Vulnerability", "Product Vulnerability"),
    ("Vendor Incident", "Vendor Incident"),
)
severity = (
    ("Low", "Low"),
    ("Medium", "Medium"),
    ("High", "High"),
    ("Critical", "Critical"),
)

class Incident(models.Model):
    what_happened = models.CharField(max_length=40, choices=incident_type)
    customer_id = models.CharField(max_length=15)
    customer_email = models.EmailField()
    when_did_it_happen = models.DateField(auto_now_add=True, editable=False)
    how_was_it_discovered = models.TextField()
    how_could_we_have_prevented_this = models.TextField()
    additional_notes = models.TextField()
    data_of_incident = models.DateField(auto_now=False)
    level = models.CharField(max_length=20, choices=severity)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        editable=True,
    )


    def __str__(self):
        return self.customer_id[:50]

    def get_absolute_url(self):
        return reverse('incidents/incident_detail', args=[str(self.id)])

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomerUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = UserCreationForm.Meta.fields

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import CustomerUserCreationForm
# Create your views here.


class SignUpView(CreateView):
    form_class = CustomerUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

api/views.py
from django.shortcuts import render
from rest_framework import generics
from incidents.models import Incident
from.serializers import IncidentSerializer
from .permissions import IsAuthorOrReadOnly
# Create your views here.

class APIList(generics.ListCreateAPIView):
    queryset = Incident.objects.all()
    serializer_class = IncidentSerializer

class APIDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (IsAuthorOrReadOnly,)
    queryset = Incident.objects.all()
    serializer_class = IncidentSerializer

customers/views.py
from django.shortcuts import render

# Create your views here.

incidents/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin
)
from django.views.generic import ListView, DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView
)
from django.urls import reverse_lazy
from incidents.models import Incident


# [LoginRequiredMixin] added to restrict view access to only logged-in users
# Class for the ListView functionality
class HomeListView(LoginRequiredMixin, ListView):
    model = Incident
    template_name = 'incidents/incident_list.html'


# [LoginRequiredMixin] added to restrict view access to only logged-in users
# Class for the DetailView functionality
class HomeDetailView(LoginRequiredMixin, DetailView):
    model = Incident
    template_name = 'incidents/incident_detail.html'


# [LoginRequiredMixin] added to restrict view access to only logged-in users
# class for the CreateView functionality
class HomeCreateView(LoginRequiredMixin, CreateView):
    model = Incident
    template_name = 'incidents/incident_new.html'
    fields = ['what_happened', 'customer_id', 'customer_email', 'how_was_it_discovered',
              'how_could_we_have_prevented_this', 'additional_notes', 'data_of_incident', 'level']

    # Create a function that automatically sets the author field.
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


# [LoginRequiredMixin] added to restrict view access to only logged-in users
# Class for the UpdateView functionality
class HomeUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Incident
    template_name = 'incidents/incident_edit.html'
    fields = ['what_happened', 'customer_id', 'customer_email', 'how_was_it_discovered',
              'how_could_we_have_prevented_this', 'additional_notes', 'data_of_incident', 'level']

    # [UserPassesTestMixin] Restricts access so only the author of the Incident has permission to Update
    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


# [LoginRequiredMixin] added to restrict view access to only logged-in users
# Class for the DeleteView functionality
class HomeDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Incident
    template_name = 'incidents/incident_delete.html'
    success_url = reverse_lazy('home')

    # [UserPassesTestMixin] Restricts access so only the author of the Incident has permission to Delete
    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.


# Default HomePage View
class HomePageView(TemplateView):
    template_name = 'home.html'

templates/base.html
{% load static %}
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}Incident Response{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body>
    <header>
    <!-- Fixed navbar -->
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4
            mb-3 bg-white border-bottom shadow-sm">
            <a href="{% url 'home' %}" class="navbar-brand my-0 mr-md-auto font-weight-normal"><h1>Collective Vega</h1></a>
            <img src="https://img.icons8.com/cotton/64/000000/bear.png"/>
            <nav class="my-2 my-md-0 mr-md-3">
                {% if user.is_authenticated %}
                    <a class="p-2 text-dark" href="{% url 'incidents/incident_list' %}">Incidents</a>

                    <a class="p-2 text-dark" href="{% url 'logout' %}">Log Out</a>
                {% else %}
                    <a class="btn btn-outline-primary" href="{% url 'login' %}">Log In</a>
                    <a class="btn btn-outline-primary" href="{% url 'signup' %}">Sign Up</a>
                {% endif %}
            </nav>
        </div>
    </header>
    <div class="container">
            {% block content %}
            {% endblock content %}
    </div>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <footer>
        <div class="footer-copyright text-center py-3">
            <p>Made with <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-balloon-heart-fill" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M8.49 10.92C19.412 3.382 11.28-2.387 8 .986 4.719-2.387-3.413 3.382 7.51 10.92l-.234.468a.25.25 0 1 0 .448.224l.04-.08c.009.17.024.315.051.45.068.344.208.622.448 1.102l.013.028c.212.422.182.85.05 1.246-.135.402-.366.751-.534 1.003a.25.25 0 0 0 .416.278l.004-.007c.166-.248.431-.646.588-1.115.16-.479.212-1.051-.076-1.629-.258-.515-.365-.732-.419-1.004a2.376 2.376 0 0 1-.037-.289l.008.017a.25.25 0 1 0 .448-.224l-.235-.468ZM6.726 1.269c-1.167-.61-2.8-.142-3.454 1.135-.237.463-.36 1.08-.202 1.85.055.27.467.197.527-.071.285-1.256 1.177-2.462 2.989-2.528.234-.008.348-.278.14-.386Z"/>
            </svg> by Susbot</p>
        </div>
    </footer>


</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}




    {% if user.is_authenticated %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">Welcome to Collective Vega V2 </h1>
            <p class="lead">Submit an incident below</p>
        </div>
    </div>
    {% else %}

    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h2 class="display-4">Welcome to Version 2 </h2>
            <p class="lead">Incident Response forms streamlined</p>
            <p class="lead">Please take a moment to Sign up and explore further.</p>
        </div>

        <div class="container">
            <p class="lead">Username: demo</p>
            <p class="lead">Password: demodemo</p>
        </div>
    </div>
     {% endif %}



    {% if user.is_authenticated %}
    <br/>
        <a class="btn btn-primary btn-lg btn-block" href="{% url 'incidents/incident_new' %}">New Incident</a>
    <br/>

    {% endif %}
{% endblock content %}

templates/incidents/incident_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Post</h1>
    <form action="" method="post">
        {% csrf_token %}
        <P>Are you sure you want to delete customer incident: {{ incident.customer_id }}?</P>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
        <a class="btn btn-warning" href="{% url 'incidents/incident_list' %}">Cancel</a>
    </form>
{% endblock content %}

templates/incidents/incident_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="post-entry">

        <ul class="list-group">
            <li class="list-group-item list-group-item-danger" aria-disabled="true">Severity Level: {{ incident.level }}</li>
            <li class="list-group-item">What happend : {{ incident.what_happened }}</li>
            <li class="list-group-item">Customer ID: {{ incident.customer_id }}</li>
            <li class="list-group-item">Customer email: {{ incident.customer_email }}</li>
            <li class="list-group-item">When did it happen ?: {{ incident.when_did_it_happen }}</li>
            <li class="list-group-item">How was it discovered ?: {{ incident.how_was_it_discovered }}</li>
            <li class="list-group-item">How could we have prevented this ?: {{ incident.how_could_we_have_prevented_this }}</li>
            <li class="list-group-item">Additional Notes: {{ incident.additional_notes }}</li>
            <li class="list-group-item">Date of Incident: {{ incident.data_of_incident }}</li>
            <li class="list-group-item">Author of Report: {{ incident.author }}</li>
        </ul>

    </div>

    <a class="btn btn-warning" href="{% url 'incidents/incident_edit' incident.pk %}">Edit Incident</a>
    <a class="btn btn-danger" href="{% url 'incidents/incident_delete' incident.pk %}">Delete Incident</a>
    <a class="btn btn-dark" href="{% url 'incidents/incident_list' %}">Go Back</a>

{% endblock content %}

templates/incidents/incident_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Edit</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-info ml-2" type="submit">Update</button>
        <a class="btn btn-dark" href="{% url 'incidents/incident_list' %}">Go Back</a>
    </form>
{% endblock content %}

templates/incidents/incident_list.html
{% extends 'base.html' %}

{% block title %}Incident List {% endblock title %}

{% block content %}
    <div>
        <a class="btn btn-primary btn-lg btn-block" href="{% url 'incidents/incident_new' %}">New Incident</a>
    </div>
    <br />
    {% for incident in object_list %}
        <div class="card border-dark mb-3">
        <div class="card">
            <div class="card-header">
                <p class="list-group-item list-group-item-danger" aria-disabled="true">Severity Level: {{ incident.level }}</p>
                <span class="text-muted">
                </span>
            </div>
            <div class="card-body">
                <p class="list-group-item">Customer ID: {{ incident.customer_id }} </p>
                <p class="list-group-item">Customer Email: {{ incident.customer_email }} </p>
                <p class="list-group-item">Author of Report: {{ incident.author }}</p>
            </div>
            <div class="card-footer text-center text-muted">
                <a class="btn btn-success" href="{% url 'incidents/incident_detail' incident.pk %}">Details</a>
                <a class="btn btn-warning" href="{% url 'incidents/incident_edit' incident.pk %}">Edit Incident</a>
                <a class="btn btn-danger" href="{% url 'incidents/incident_delete' incident.pk %}">Delete Incident</a>
                <a class="btn btn-dark" href="">Set Reminder</a>

            </div>
        </div>
            <br />
        </div>
    {% endfor %}
{% endblock content %}


    {% if incident.get_level_display ==  Critical %}
        <p class="list-group-item list-group-item-primary" aria-disabled="true">Severity Level: {{ incident.level }}</p>
    {% else %}
        <p class="list-group-item list-group-item-danger" aria-disabled="true">Severity Level: {{ incident.level }}</p>
    {% endif %}

   <p>Severity level {{incident.get_level_display }}</p>

templates/incidents/incident_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h1>New Incident</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success ml-2" type="submit">Save</button>
        <a class="btn btn-warning" href="{% url 'incidents/incident_list' %}">Cancel</a>
    </form>
{% endblock content %}